### PR TITLE
Callbacks for third party integrations

### PR DESCRIPTION
**Pull request by isaacbernat**
[Live example](http://isaacbernat.github.io/rhythm-radar/) of one such integration along with [its codebase](https://github.com/isaacbernat/rhythm-radar)

### CODE REVIEW

**Comment by montulli** [comment]
Does callback need to be checked for nil before calling in timeSigPopupClose?

**Comment by isaacbernat** [comment]
Yes, absolutely! It's fixed now, thanks!

**Comment by isaacbernat** [comment]
Are there any more changes you'd like me to do on the PR?

**Comment by montulli** [comment]
Sorry for the delay.   My regular work has been consuming all my time.    Thanks for the contribution.  Please let me know if I can help or if you find bugs or have feature requests.

**Pull request merged**
